---
- name: install/update postgresql
  homebrew: name=postgresql state=latest

- name: ensure ~/Library/LaunchAgents directory exists
  file: path=~/Library/LaunchAgents state=directory

- name: ensure postgresql launch agent is installed
  file:
  args:
    src: /usr/local/opt/postgresql/homebrew.mxcl.postgresql.plist
    path: ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
    state: link
  notify: start postgresql
