---
- name: install/update mongodb
  homebrew: name=mongodb state=latest

- name: ensure ~/Library/LaunchAgents directory exists
  file: path=~/Library/LaunchAgents state=directory

- name: ensure mongodb launch agent is installed
  file:
  args:
    src: /usr/local/opt/mongodb/homebrew.mxcl.mongodb.plist
    path: ~/Library/LaunchAgents/homebrew.mxcl.mongodb.plist
    state: link
  notify: start mongodb
