---
- name: install/update tmux
  homebrew: name=tmux state=latest

- name: add common tmux configuration
  copy: src=common.tmux dest={{ stack_d }}
  notify: update tmux config

- name: add tmux plugins to vim
  copy: src=tmux.bundle dest={{ stack_d }}/tmux.bundle
  notify: vim bundle install

- name: add tmux zsh configuration
  copy: src=tmux.zsh dest={{ stack_d }}

- name: ensure ~/Library/Fonts directory exists
  file: path=~/Library/Fonts state=directory

- name: tap caskroom/cask so that brew-cask can be installed
  homebrew_tap: tap=caskroom/cask state=present

- name: install/update brew cask
  homebrew: name=brew-cask state=latest

- name: tap caskroom/fonts
  homebrew_tap: tap=caskroom/fonts state=present

- name: ensure inconsolata-g exists
  homebrew_cask: name=font-inconsolata-g-for-powerline state=present
