---
- name: install/update nvm
  homebrew: name=nvm state=head

- name: add nvm configuration to zsh
  copy: src=nvm.zsh dest={{ zshrc_d }}

- name: install node versions
  shell: source $(brew --prefix nvm)/nvm.sh && nvm install {{ item }}
  with_items:
    - stable
    - iojs
  register: nvm_install_result
  changed_when: "'already installed' not in nvm_install_result.stderr"
